export const AI_COLOR_DOCUMENTATION_LINES = [
  'Default fill-color word map (use exact palette hex values):',
  '- white -> #FFFFFF',
  '- green -> #C6EFCE',
  '- yellow -> #FFEB9C',
  '- orange -> #F4B183',
  '- red -> #FFC7CE',
  '- purple -> #D9C2E9',
  '- blue -> #BDD7EE',
  '- If the user asks for a named color, emit the mapped hex exactly. Do not substitute another color.',
] as const;

export const AI_AUTHORING_IR_DOCUMENTATION_LINES = [
  'Authoring operands:',
  '- column operand: { "source": "column", "columnId": "col_x" }',
  '- scoped current-cell operand: { "source": "value" }',
  '- current match subject operand: { "source": "caseValue" }',
  '- literal operand: { "source": "literal", "value": "text" | 123 | true | false | null }',
  '- Use { "source": "value" } only inside scopedRule conditions and cell patch values.',
  '- Use { "source": "caseValue" } only inside match.cases[*].when and match.cases[*].then.',
  '',
  'Value expression shapes:',
  '- nullary: { "kind": "nullary", "op": "now" }',
  '- unary: { "kind": "unary", "op": "trim"|"lower"|"upper"|"toNumber"|"toString"|"toBoolean"|"collapseWhitespace"|"first"|"last"|"length"|"round"|"floor"|"ceil"|"abs", "input": <value expression> }',
  '- binary: { "kind": "binary", "op": "split"|"atIndex"|"extractRegex"|"add"|"subtract"|"multiply"|"divide"|"modulo"|"datePart", "left": <value expression>, "right": <value expression> }',
  '- ternary: { "kind": "ternary", "op": "substring"|"replace"|"replaceRegex"|"dateDiff"|"dateAdd", "first": <value expression>, "second": <value expression>, "third": <value expression> }',
  '- nary: { "kind": "nary", "op": "concat"|"coalesce", "items": [<value expression>, ...] }',
  '- match: { "kind": "match", "subject": <value expression>, "cases": [{ "kind": "when", "when": <boolean expression>, "then": <value expression> }, { "kind": "otherwise", "then": <value expression> }] }',
  '',
  'Boolean expression shapes:',
  '- predicate: { "kind": "predicate", "op": "isEmpty", "input": <value expression> }',
  '- compare: { "kind": "compare", "op": "eq"|"gt"|"lt"|"gte"|"lte"|"contains"|"startsWith"|"endsWith"|"matchesRegex", "left": <value expression>, "right": <value expression> }',
  '- between: { "kind": "between", "input": <value expression>, "min": <value expression>, "max": <value expression>, "inclusiveMin": true|false, "inclusiveMax": true|false }',
  '- boolean group: { "kind": "boolean", "op": "and"|"or", "items": [<boolean expression>, ...] }',
  '- boolean not: { "kind": "boolean", "op": "not", "item": <boolean expression> }',
] as const;

export const AI_OPERATOR_DOCUMENTATION_LINES = [
  'Operator input type requirements (critical):',
  '- String-like means logical type string or unknown. Number-like means logical type number or unknown.',
  '- trim/lower/upper/collapseWhitespace require string-like input.',
  '- toNumber/toString/toBoolean require scalar input.',
  '- first/last/length require a string-like input or a list input.',
  '- split requires (string-like text, string-like delimiter).',
  '- atIndex requires (string-like or list input, number-like index).',
  '- extractRegex requires (string-like text, string-like pattern).',
  '- substring requires (string-like text, number-like start, number-like length).',
  '- replace and replaceRegex require three string-like inputs.',
  '- add/subtract/multiply/divide/modulo require number-like left and right inputs.',
  '- round/floor/ceil/abs require a number-like input.',
  '- datePart requires (date/datetime/string-like value, string-like unit literal).',
  '- dateDiff requires (date/datetime/string-like left, date/datetime/string-like right, string-like unit literal).',
  '- dateAdd requires (date/datetime/string-like value, number-like amount, string-like unit literal).',
  '- isEmpty requires scalar input. not requires boolean-like input. and/or require boolean-like inputs.',
  '- eq requires comparable scalar inputs. gt/lt/gte/lte/between require comparable ordered scalar inputs.',
  '- contains/startsWith/endsWith/matchesRegex require string-like inputs.',
  '- concat requires at least two scalar inputs. coalesce requires one or more scalar items of one compatible non-mixed type.',
  '',
  'Operator literal and behavior specifics (critical):',
  '- datePart unit literals are singular: "year", "month", "day", "dayOfWeek", "hour", "minute", "second".',
  '- dateDiff and dateAdd duration unit literals are plural: "years", "months", "days", "hours", "minutes", "seconds".',
  '- For account age in days, use dateDiff(now(), <signup date>, "days"). Do not use "day" for dateDiff.',
  '- dateDiff(a, b, unit) returns a - b. For elapsed age since a past date, put now() first and the past date second.',
  '- substring(text, start, length) uses a zero-based start and a length, not an end index.',
  '- atIndex(textOrList, index) uses a zero-based index.',
  '- length(textOrList) returns the number of characters in a string or items in a list.',
  '- replace uses exact literal text. replaceRegex, extractRegex, and matchesRegex use regex pattern strings.',
  '- concat joins values with no separator. Include literal separators like " " when needed.',
  '- coalesce is always nary: { "kind": "nary", "op": "coalesce", "items": [a, b, ...] }. Never emit coalesce as kind "unary", "binary", or "ternary".',
  '- coalesce selects the first value that is not null and not "". Use match/isEmpty on trimmed values when whitespace-only strings should count as missing.',
  '- contains, startsWith, endsWith, and matchesRegex are case-sensitive. Normalize with lower(...) when matching case-insensitively.',
] as const;

export const AI_CANONICAL_RUNTIME_DOCUMENTATION_LINES = [
  'Canonical Workflow IR semantics:',
  '- Steps execute top to bottom. Later steps see values and columns created or changed by earlier steps.',
  '- scopedRule is a cell-level rewrite/format step. For each targeted cell, cases are checked in order against the current cell value.',
  '- In scopedRule, then.value assigns/replaces the target cell value. It is not merely a returned expression.',
  '- A later scopedRule targeting the same column sees the value assigned by an earlier scopedRule.',
  '- Therefore, a scopedRule that fills Email from Email (2), followed by a scopedRule that trims/lowercases Email, satisfies "fall back, then normalize the final Email".',
  '- isEmpty(...) treats null, empty strings, and whitespace-only strings as empty.',
  '- isEmpty(trim(x)) is also a valid way to express whitespace-empty handling.',
  '- match cases are ordered and first-match-wins. caseValue refers to the current match subject.',
  '- Compiled canonical drafts use call names such as equals, greaterThan, lessThan, contains, startsWith, endsWith, and matchesRegex. These are valid canonical calls.',
  '- Authoring compare ops eq/gt/lt/gte/lte compile to canonical calls such as equals, greaterThan, lessThan, or boolean combinations of those calls.',
  '- When reviewing a compiled canonical draft, do not fail it just because it uses canonical call names instead of authoring operator aliases.',
] as const;

export const AI_SHARED_IMPLEMENTATION_DOCUMENTATION_LINES = [
  'Shared Scratch My Table implementation documentation:',
  ...AI_COLOR_DOCUMENTATION_LINES,
  '',
  ...AI_OPERATOR_DOCUMENTATION_LINES,
  '',
  ...AI_CANONICAL_RUNTIME_DOCUMENTATION_LINES,
] as const;

export function buildSharedImplementationDocumentation() {
  return [...AI_SHARED_IMPLEMENTATION_DOCUMENTATION_LINES];
}
